#%RAML 0.8
title: Sample API

/usZipValidation:
  description: Validation of zipCode based on address
  get:
    description: Request to web service for validation of address
    responses:
      200:
        body:
          application/json:
     